spring:
  mail:
    host: smtp.exmail.qq.com
    port: 465
    password: z6zG9MjKHFQxApx7
    username: notice@chenyuzhifu.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true