spring:
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true